version: "3"

services:
  postgesql:
    image: postgres:latest
    container_name: bot_reminder
    ports:
      - 5000:5432
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reminder
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
    - ./rabbitmq/data/:/var/lib/rabbitmq/
    - ./rabbitmq/log/:/var/log/rabbitmq